name: Run Playwright Sum by 24f2004718@ds.study.iitm.ac.in

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Playwright Script by 24f2004718@ds.study.iitm.ac.in
        run: node sum-tables.js
